//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuaHang_SanPham
    {
        public int CuaHang_Id { get; set; }
        public int SanPham_Id { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual CuaHang CuaHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
