//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int Id { get; set; }
        public byte[] NgayTao { get; set; }
        public int NhaCC_Id { get; set; }
        public decimal ThanhTien { get; set; }
        public int KhachHang_Id { get; set; }
        public int CuaHang_Id { get; set; }
        public int NhanVien_Id { get; set; }
        public string ChuongTrinh_Id { get; set; }
    }
}
