//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int Id { get; set; }
        public string Ten_KhachHang { get; set; }
        public string Email_KhachHang { get; set; }
        public string Pass_KhachHang { get; set; }
        public Nullable<byte> GioiTinh_KhachHang { get; set; }
        public Nullable<int> Diem_KhachHang { get; set; }
        public Nullable<int> ChucVu_Id { get; set; }
        public string DiaChi_KhachHang { get; set; }
        public byte[] Avatar_KhachHang { get; set; }
    
        public virtual QuyenHan QuyenHan { get; set; }
    }
}
