//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int Id { get; set; }
        public string Ten_NhanVien { get; set; }
        public byte[] NgaySinh { get; set; }
        public Nullable<int> ChucVu_Id { get; set; }
        public string DiaChi_NhanVien { get; set; }
        public Nullable<int> CuaHang_Id { get; set; }
    
        public virtual QuyenHan QuyenHan { get; set; }
        public virtual CuaHang CuaHang { get; set; }
    }
}
