//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuangCao
    {
        public string Id { get; set; }
        public string Ten_ChuongTrinh { get; set; }
        public string MoTa_ChuongTrinh { get; set; }
        public byte[] HinhAnh_ChuongTrinh { get; set; }
    }
}
