//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenHan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuyenHan()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int Id { get; set; }
        public string Ten_ChucVu { get; set; }
        public Nullable<byte> Tao_Order { get; set; }
        public Nullable<byte> Sua_Order { get; set; }
        public Nullable<byte> Huy_Order { get; set; }
        public Nullable<byte> Tao_Taikhoan { get; set; }
        public Nullable<byte> Sua_TaiKhoan { get; set; }
        public Nullable<byte> Disable_TaiKhoan { get; set; }
        public Nullable<byte> TonKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
